<a href="https://colab.research.google.com/github/hyakuroume/-/blob/main/NumPy_%E3%81%A7NN%E5%AE%9F%E8%A3%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# 重み 2行3列
np.random.seed(1)
W1 = np.random.randn(2, 3)
W1

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ]])

In [3]:
# バイアス
b1 = np.random.randn(3)
b1

array([ 1.74481176, -0.7612069 ,  0.3190391 ])

In [4]:
# サンプル数10, 入力変数２
X = np.random.randn(10,2)
X

array([[-0.24937038,  1.46210794],
       [-2.06014071, -0.3224172 ],
       [-0.38405435,  1.13376944],
       [-1.09989127, -0.17242821],
       [-0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918],
       [ 1.14472371,  0.90159072],
       [ 0.50249434,  0.90085595],
       [-0.68372786, -0.12289023],
       [-0.93576943, -0.26788808]])

In [5]:
X.shape

(10, 2)

In [6]:
W1.shape

(2, 3)

In [7]:

u1 = np.dot(X, W1) + b1
u1

array([[-0.22904779,  0.65666639, -2.91434851],
       [-1.2556247 ,  0.22007508,  2.1492029 ],
       [-0.09552418,  0.45491354, -2.08752849],
       [ 0.14321854, -0.23756205,  1.29682079],
       [ 0.27357249, -0.18763928,  0.68554254],
       [ 3.8724348 , -2.07023208,  2.54433019],
       [ 2.63685986, -0.68125548, -2.36061756],
       [ 1.59444595, -0.28900342, -2.01971905],
       [ 0.76605894, -0.44928214,  0.96300145],
       [ 0.51223453, -0.42057634,  1.42984086]])

In [8]:
u1.shape

(10, 3)

シグモイド関数
$$f(x)= \frac{x}{1+e^{-x}} $$

In [9]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [10]:
sigmoid(u1)

array([[0.44298709, 0.65851114, 0.05144881],
       [0.22172799, 0.55479778, 0.89559427],
       [0.4761371 , 0.61180683, 0.11031491],
       [0.53574356, 0.44088723, 0.78529944],
       [0.56796973, 0.45322733, 0.66497461],
       [0.97961649, 0.11202395, 0.92719169],
       [0.93319647, 0.33598115, 0.08622552],
       [0.8312407 , 0.42824786, 0.11714805],
       [0.68266775, 0.38953146, 0.72372234],
       [0.62533015, 0.39637885, 0.80687652]])

ReLU関数
$$f(x) = \max(0,x)$$

In [11]:
# ReLU
def relu(x):
    return np.maximum(0, x)

In [12]:
# 中間層の出力
z1 = relu(u1)
z1

array([[0.        , 0.65666639, 0.        ],
       [0.        , 0.22007508, 2.1492029 ],
       [0.        , 0.45491354, 0.        ],
       [0.14321854, 0.        , 1.29682079],
       [0.27357249, 0.        , 0.68554254],
       [3.8724348 , 0.        , 2.54433019],
       [2.63685986, 0.        , 0.        ],
       [1.59444595, 0.        , 0.        ],
       [0.76605894, 0.        , 0.96300145],
       [0.51223453, 0.        , 1.42984086]])

#中間層から出力層

In [13]:
W2 = np.random.randn(3, 2)
W2

array([[ 0.53035547, -0.69166075],
       [-0.39675353, -0.6871727 ],
       [-0.84520564, -0.67124613]])

In [14]:
b2 = np.random.randn(2)
b2

array([-0.0126646 , -1.11731035])

In [15]:
u2 = np.dot(z1, W2) + b2
u2

array([[-0.2731993 , -1.56855356],
       [-1.91649858, -2.71118407],
       [-0.19315315, -1.42991451],
       [-1.03278811, -2.08685493],
       [-0.44699836, -1.76669748],
       [-0.10937987, -5.50359331],
       [ 1.38580844, -2.94112282],
       [ 0.83295853, -2.22012603],
       [-0.42031531, -2.29357425],
       [-0.94950778, -2.43137801]])

In [16]:
#ソフトマックス
# x から np.max(x))を引くことでオーバーフロー（桁あふれ）を防ぐ
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

In [17]:
y = softmax(u2[0])
y

array([0.78505207, 0.21494793])

In [18]:
# インデックス番号を返す
np.argmax(y)

0

In [19]:
def softmax(x):
    if x.ndim == 2:
        x = x - x.max(axis=1, keepdims=True)
        x = np.exp(x)
        x /= x.sum(axis=1, keepdims=True)

    elif x.ndim == 1:
        x = x - np.max(x)
        x = np.exp(x) / np.sum(np.exp(x))

    return x

In [20]:
softmax(u2[0])

array([0.78505207, 0.21494793])

In [21]:
softmax(u2)

array([[0.78505207, 0.21494793],
       [0.68883651, 0.31116349],
       [0.77499978, 0.22500022],
       [0.74155508, 0.25844492],
       [0.78913164, 0.21086836],
       [0.99547775, 0.00452225],
       [0.98696416, 0.01303584],
       [0.95491551, 0.04508449],
       [0.86683491, 0.13316509],
       [0.8148549 , 0.1851451 ]])

# レイヤとしてまとめていく

- 変数
 - パラメータ(params)
 - 勾配(grads)

- メソッド
 - 順伝播(forward)
 - 逆伝播(backward)

### Affine変換(線形変換)

In [22]:
class Affine:
    # パラメータの初期化
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

### ReLU関数(非線形変換)

In [23]:
class ReLU:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return np.maximum(0, x)

In [24]:
# 重みとバイアス
W1 = np.random.randn(2, 3)
b1 = np.random.randn(3)

W2 = np.random.randn(3, 2)
b2 = np.random.randn(2)

In [25]:
class NN:
    def __init__(self, n_in, n_hidden, n_out):

        # W, bの初期化
        W1 = np.random.randn(n_in, n_hidden)
        b1 = np.random.randn(n_hidden)

        W2 = np.random.randn(n_hidden, n_out)
        b2 = np.random.randn(n_out)

        # レイヤをまとめる
        self.layers = [
            Affine(W1, b1),
            ReLU(),
            Affine(W2, b2)
        ]

        # パラメータをまとめる
        self.params = []

        for layer in self.layers:
            self.params += layer.params

    # 推論
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [26]:
x = np.random.randn(10, 4)
x

array([[-0.20889423,  0.58662319,  0.83898341,  0.93110208],
       [ 0.28558733,  0.88514116, -0.75439794,  1.25286816],
       [ 0.51292982, -0.29809284,  0.48851815, -0.07557171],
       [ 1.13162939,  1.51981682,  2.18557541, -1.39649634],
       [-1.44411381, -0.50446586,  0.16003707,  0.87616892],
       [ 0.31563495, -2.02220122, -0.30620401,  0.82797464],
       [ 0.23009474,  0.76201118, -0.22232814, -0.20075807],
       [ 0.18656139,  0.41005165,  0.19829972,  0.11900865],
       [-0.67066229,  0.37756379,  0.12182127,  1.12948391],
       [ 1.19891788,  0.18515642, -0.37528495, -0.63873041]])

In [27]:
model = NN(4, 10, 3)

In [28]:
model.predict(x)

array([[ 2.68492376, -3.46662847,  1.53830454],
       [-0.87922771, -7.59345423,  5.0555068 ],
       [ 5.52278128,  2.40294997, -0.57603526],
       [19.16049855, -3.93987764, -4.25678143],
       [ 0.56456033, -2.80431995,  3.73800204],
       [ 6.45568363,  5.42097663,  1.63029789],
       [ 3.27044943, -4.17930502,  1.21745043],
       [ 3.30977113, -2.94604386,  0.83673536],
       [-0.34737662, -5.12561645,  3.89873707],
       [ 4.73351937, -0.90182198,  0.54144564]])

# 逆伝播

### Affine

In [29]:
class Affine:
    # パラメータの初期化
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None

    # 順伝播
    def forward(self, x):
        self.x = x
        W, b = self.params
        out = np.dot(x, W) + b
        return out

    # 逆伝播
    def backward(self, dout):
        W, b = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db

        return dx

### Sigmoid

In [35]:
class Sigmoid:

    def __init__(self):
        self.params = []
        self.grads = []
        self.out = None

    def forward(self, x):
        out = 1 / (1+np.exp(-x))
        self.out = out
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out)*self.out
        return dx

In [36]:
sigmoid = Sigmoid()

In [37]:
x

array([[-0.20889423,  0.58662319,  0.83898341,  0.93110208],
       [ 0.28558733,  0.88514116, -0.75439794,  1.25286816],
       [ 0.51292982, -0.29809284,  0.48851815, -0.07557171],
       [ 1.13162939,  1.51981682,  2.18557541, -1.39649634],
       [-1.44411381, -0.50446586,  0.16003707,  0.87616892],
       [ 0.31563495, -2.02220122, -0.30620401,  0.82797464],
       [ 0.23009474,  0.76201118, -0.22232814, -0.20075807],
       [ 0.18656139,  0.41005165,  0.19829972,  0.11900865],
       [-0.67066229,  0.37756379,  0.12182127,  1.12948391],
       [ 1.19891788,  0.18515642, -0.37528495, -0.63873041]])

In [38]:
sigmoid.forward(x)

array([[0.44796552, 0.64258997, 0.69825107, 0.71729882],
       [0.5709155 , 0.70788646, 0.31986377, 0.77779596],
       [0.62549304, 0.42602377, 0.61975728, 0.48111606],
       [0.75613947, 0.8205115 , 0.89894668, 0.19837268],
       [0.19090911, 0.37649175, 0.53992409, 0.7060277 ],
       [0.57826009, 0.11689157, 0.42404157, 0.69592651],
       [0.55727123, 0.68179022, 0.44464579, 0.44997838],
       [0.54650554, 0.60110026, 0.54941311, 0.5297171 ],
       [0.33834856, 0.59328538, 0.53041771, 0.75574364],
       [0.76833222, 0.54615731, 0.40726461, 0.34553359]])

### ReLU

In [39]:
class Relu:

    def __init__(self):
        self.params = []
        self.grads = []
        self.x = None

    def forward(self, x):
        self.x = x
        return np.maximum(0, self.x)

    def backward(self, dout):
        return np.where(self.x > 0, dout, 0)

In [40]:
x = np.array([1, 2, 4, -3])
dout = np.array([1, 3, 4, 5])

In [41]:
relu = Relu()

In [42]:
# 順伝播
relu.forward(x)

array([1, 2, 4, 0])

In [43]:
# 逆伝播
relu.backward(dout)

array([1, 3, 4, 0])